version: 0.2

phases:
  build:
    commands:
      - echo Build and push with Jib...
      - chmod +x gradlew
      - ./gradlew --no-daemon clean jib -Djib.to.image=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG -Djib.to.auth.username=AWS -Djib.to.auth.password=$(aws ecr get-login-password --region $AWS_REGION) -Djib.container.ports=8081