sonar.projectKey=practice_aws_service
sonar.projectName=practice_aws_service
sonar.sourceEncoding=UTF-8
sonar.java.source=25
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
